app:
  security:
    jwt:
      secret: "dev-secret-change-me-dev-secret-change-me"
    google:
      client-id: "505213355065-2bupm12mn12g2058edf3givhmu3enqgh.apps.googleusercontent.com"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mambasplit
    username: mambasplit
    password: mambasplit
