server:
  port: 8080

app:
  security:
    jwt:
      issuer: "mambasplit-api"
      secret: ${APP_SECURITY_JWT_SECRET}
      accessTokenMinutes: 15
      refreshTokenDays: 30

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
